import {
  Clock,
  EyeOff,
  Receipt,
  Unlink,
  DatabaseZap,
  ScanSearch,
  Users,
  ShieldCheck,
  Landmark,
  Building2,
  Scale,
  CandlestickChart,
  Layers,
  Network,
  BrainCircuit,
  HardDrive,
  FlaskConical,
  Rocket,
  Globe2,
  Trophy,
  Coins,
  Lock,
  Flame,
  Vote,
  Handshake,
  Code2,
  Mail,
  type LucideIcon,
} from "lucide-react";

// Semantic icon registry — every key maps to a lucide-react icon chosen
// to match the meaning of the content it represents (never decorative-only).
export const iconMap: Record<string, LucideIcon> = {
  clock: Clock,
  eyeOff: EyeOff,
  receipt: Receipt,
  unlink: Unlink,
  databaseZap: DatabaseZap,
  scanSearch: ScanSearch,
  users: Users,
  shieldCheck: ShieldCheck,
  landmark: Landmark,
  building2: Building2,
  scale: Scale,
  candlestickChart: CandlestickChart,
  layers: Layers,
  network: Network,
  brainCircuit: BrainCircuit,
  hardDrive: HardDrive,
  flaskConical: FlaskConical,
  rocket: Rocket,
  globe2: Globe2,
  trophy: Trophy,
  coins: Coins,
  lock: Lock,
  flame: Flame,
  vote: Vote,
  handshake: Handshake,
  code2: Code2,
  mail: Mail,
};

export function getIcon(key: string): LucideIcon {
  return iconMap[key] ?? Network;
}
