import type { CSSProperties } from "react";
import {
  WORLD_MAP_WIDTH,
  WORLD_MAP_HEIGHT,
  WORLD_LAND_PATH,
  VALIDATOR_REGIONS,
} from "./worldMapData";

// Label placement per region — offset + text-anchor tuned by hand so
// labels near map edges (Sydney, Singapore) stay readable.
const LABEL_LAYOUT: Record<string, { dx: number; dy: number; anchor: "start" | "middle" | "end" }> = {
  Frankfurt: { dx: 10, dy: -6, anchor: "start" },
  "New York": { dx: -10, dy: -6, anchor: "end" },
  "São Paulo": { dx: -10, dy: 5, anchor: "end" },
  Singapore: { dx: 10, dy: 16, anchor: "start" },
  Sydney: { dx: -10, dy: 16, anchor: "end" },
};

// transform-box keeps the pulsing "radar" circle's scale animation centered
// on the marker itself instead of the SVG's (0,0) origin.
const pingStyle: CSSProperties = { transformBox: "fill-box", transformOrigin: "center" };

/**
 * Real-world map (Natural Earth projection, world-atlas countries-110m,
 * pre-generated by scripts/generate-world-map.cjs — see worldMapData.ts)
 * with pulsing markers over Trayon's anchor validator regions. Pure SVG +
 * CSS animation: no client JS, no map tiles, no runtime geo libraries.
 */
export function WorldMap() {
  return (
    <svg
      viewBox={`0 0 ${WORLD_MAP_WIDTH} ${WORLD_MAP_HEIGHT}`}
      className="h-auto w-full"
      role="img"
      aria-label="World map highlighting Trayon validator regions: Frankfurt, New York, São Paulo, Singapore, and Sydney"
    >
      {/* Latitude/longitude guide lines for a subtle "globe grid" feel */}
      <g stroke="var(--border)" strokeWidth={1} opacity={0.5}>
        <line x1="0" y1={WORLD_MAP_HEIGHT / 2} x2={WORLD_MAP_WIDTH} y2={WORLD_MAP_HEIGHT / 2} />
        <line x1={WORLD_MAP_WIDTH / 2} y1="0" x2={WORLD_MAP_WIDTH / 2} y2={WORLD_MAP_HEIGHT} />
      </g>

      {/* Real country silhouettes (merged landmass, Natural Earth projection) */}
      <path d={WORLD_LAND_PATH} fill="var(--border)" fillRule="evenodd" />

      {/* Validator region markers */}
      {VALIDATOR_REGIONS.map((region) => {
        const layout = LABEL_LAYOUT[region.name] ?? { dx: 10, dy: -8, anchor: "start" as const };
        return (
          <g key={region.name}>
            <circle
              cx={region.x}
              cy={region.y}
              r={7}
              fill="var(--accent)"
              opacity={0.4}
              className="animate-ping"
              style={pingStyle}
            />
            <circle cx={region.x} cy={region.y} r={3.5} fill="var(--accent)" />
            <circle
              cx={region.x}
              cy={region.y}
              r={3.5}
              fill="none"
              stroke="var(--background)"
              strokeWidth={1}
            />
            <text
              x={region.x + layout.dx}
              y={region.y + layout.dy}
              textAnchor={layout.anchor}
              fontSize={14}
              fontWeight={500}
              fill="var(--foreground)"
            >
              {region.name}
            </text>
          </g>
        );
      })}
    </svg>
  );
}
